[package]
name = "src"
version = "1.4.0"
cairo-version = "2.7.0"

[dependencies]
cairo_test = "2.7.0"
starknet = "2.7.0"

[tool.NodeGuardians]
part_1 = "Brainfuck Program"
part_2 = "Brainfuck VM"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest../.