[package]
name = "src"
version = "1.2.0"
cairo-version = "2.7.0"

[[target.starknet-contract]]

[dependencies]
cairo_test = "2.7.0"
starknet = "2.7.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest